"""Collect every source used by the data and the limit lines into one bibliography.

Writes docs/REFERENCES.md (grouped by chart) and docs/references.bib.
"""

from __future__ import annotations

import re
from collections import OrderedDict

from allowed_universe import charts, loaders

DOCS = loaders.ROOT / "docs"


def _sources_for(mod) -> OrderedDict[str, str]:
    out: OrderedDict[str, str] = OrderedDict()
    for ds in mod.DATASETS:
        df = loaders.load(ds)
        for url, cit in zip(df["source_url"], df["citation"], strict=False):
            out.setdefault(url, cit)
    if hasattr(mod, "lines"):
        for line in mod.lines():
            if line.source_url:
                out.setdefault(line.source_url, line.citation)
    if hasattr(mod, "bars"):
        from allowed_universe.charts._bars import lines_of

        for line in lines_of(mod.bars()):
            if line.source_url:
                out.setdefault(line.source_url, line.citation)
    for url, cit in getattr(mod, "EXTRA_SOURCES", ()):
        out.setdefault(url, cit)
    return out


def collect() -> OrderedDict[str, OrderedDict[str, str]]:
    return OrderedDict((m.NAME, _sources_for(m)) for m in charts.all_charts())


def _bibkey(citation: str, url: str, used: set) -> str:
    author = re.match(r"[^A-Za-z]*([A-Za-z]+)", citation)
    year = re.search(r"\b(19|20)\d{2}\b", citation)
    base = f"{author.group(1).lower() if author else 'src'}{year.group(0) if year else ''}"
    key, i = base, 1
    while key in used:
        i += 1
        key = f"{base}{chr(ord('a') + i - 1)}"
    used.add(key)
    return key


def _bib_escape(s: str) -> str:
    return s.replace("&", r"\&").replace("%", r"\%").replace("#", r"\#").replace("_", r"\_")


def write() -> None:
    DOCS.mkdir(parents=True, exist_ok=True)
    groups = collect()
    md = [
        "# References",
        "",
        "Generated by `python -m allowed_universe.build` from the `source_url` and `citation` columns of",
        "every file in `data/` and from the constants used by the limit lines. Do not edit by hand.",
        "",
    ]
    all_sources: OrderedDict[str, str] = OrderedDict()
    for chart, sources in groups.items():
        md += [f"## {chart}", ""]
        for i, (url, cit) in enumerate(sources.items(), start=1):
            md.append(f"{i}. {cit}. <{url}>")
            all_sources.setdefault(url, cit)
        md.append("")
    (DOCS / "REFERENCES.md").write_text("\n".join(md), encoding="utf-8")

    used: set = set()
    bib = []
    for url, cit in all_sources.items():
        key = _bibkey(cit, url, used)
        fields = [f"  note = {{{_bib_escape(cit)}}}", f"  url = {{{url}}}"]
        if url.startswith("https://doi.org/"):
            fields.insert(0, f"  doi = {{{url.removeprefix('https://doi.org/')}}}")
        bib.append("@misc{" + key + ",\n" + ",\n".join(fields) + "\n}\n")
    (DOCS / "references.bib").write_text("\n".join(bib), encoding="utf-8")
